### ISSUE TITLE
It stopped working a week ago..

### ISSUE THREAD

**Issue by tomniklas94** [luk1337/vapor-report#4]
here is the output: 

./report.sh 76561198068257135
/root/Downloads/vapor-report-master/node_modules/protobufjs/dist/protobuf.js:784
                throw e;
                ^

Error: Parse error at line 1: unexpected '404'
    at Parser.ProtoBuf.DotProto.ParserPrototype.parse (/root/Downloads/vapor-report-master/node_modules/protobufjs/dist/protobuf.js:779:35)
    at Function.ProtoBuf.DotProto.Parser.parse (/root/Downloads/vapor-report-master/node_modules/protobufjs/dist/protobuf.js:797:39)
    at Object.ProtoBuf.loadProto (/root/Downloads/vapor-report-master/node_modules/protobufjs/dist/protobuf.js:5086:59)
    at Object.ProtoBuf.loadProtoFile (/root/Downloads/vapor-report-master/node_modules/protobufjs/dist/protobuf.js:5132:52)
    at Object.<anonymous> (/root/Downloads/vapor-report-master/protos/protos.js:6:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
[INFO] Status : 1/7

**Comment by luk1337** [comment]
Fixed.
