### ISSUE TITLE
error (get it if I try to report somebody)

### ISSUE THREAD

**Issue by 123top** [luk1337/vapor-report#5]
undefined:5
{
^

SyntaxError: Unexpected token { in JSON at position 61
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (C:\Users\luk1337\desktop\BOT\vapor-report-master\report.js:12:19)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
[INFO] Status : 1/1

**Comment by luk1337** [comment]
Your account file is not a valid json format.
